packages:
  - software/sample-clonotypes
  - software/umap
  - software/spectratype
  - software/assembling-fasta
  - software/anarci-kabat
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.9
  '@milaboratories/ts-configs': 1.2.1
  '@platforma-sdk/workflow-tengo': 5.8.2
  '@platforma-sdk/model': 1.53.15
  '@platforma-sdk/ui-vue': 1.54.1
  '@platforma-sdk/tengo-builder': 2.4.17
  '@platforma-sdk/package-builder': 3.11.4
  '@platforma-sdk/block-tools': 2.6.47
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.54.2
  '@milaboratories/helpers': 1.13.3
  '@milaboratories/graph-maker': 1.1.224
  '@milaboratories/multi-sequence-alignment': 1.46.5
  '@milaboratories/strings': 0.1.1

  # Common dependencies - can use ^ or ~
  'vue': ^3.5.24
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vitest': ^4.0.7
  'eslint': ^9.25.1
  '@changesets/cli': ^2.29.8
  '@types/node': ^24.9.1
  'vite': ^6.2.2
  'shx': ^0.4.0

  # Block-specific dependencies
  '@milaboratories/software-pframes-conv': ^2.2.9
  '@platforma-open/milaboratories.runenv-python-3': ^1.4.9
  '@platforma-open/milaboratories.software-anarci': ^0.0.3
  'sass-embedded': ^1.77.8
  '@types/lodash.debounce': ^4.0.9
  'lodash.debounce': ^4.0.8
