packages:
  - software/sample-clonotypes
  - software/umap
  - software/spectratype
  - software/assembling-fasta
  - software/anarci-kabat
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/model': ^1.43.2
  '@platforma-sdk/ui-vue': ^1.43.2
  '@platforma-sdk/workflow-tengo': ^5.4.0
  '@platforma-sdk/block-tools': ^2.6.4

  '@platforma-sdk/test': ^1.44.7
  '@platforma-sdk/tengo-builder': ^2.3.0
  '@platforma-sdk/package-builder': ^3.8.1
  '@platforma-sdk/eslint-config': ^1.1.0
  '@milaboratories/graph-maker': ^1.1.166
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  '@milaboratories/software-pframes-conv': ^2.2.7
  '@platforma-open/milaboratories.runenv-python-3': ^1.4.9
  '@platforma-open/milaboratories.software-anarci': ^0.0.3

  'sass-embedded': ^1.77.8

  'vue': ^3.5.13
  'vue-tsc': ^2.2.10

  'typescript': ~5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.5.4

  'vite': ^6.2.2
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1


  '@changesets/cli': ^2.28.1
