packages:
  - software/sample-clonotypes
  - software/umap
  - software/spectratype
  - software/abodybuilder-2
  - software/esmfold-v1
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/model': ^1.41.6
  '@platforma-sdk/ui-vue': ^1.41.17
  '@platforma-sdk/workflow-tengo': ^4.14.1
  '@platforma-sdk/block-tools': ^2.5.74
  '@platforma-sdk/test': ^1.41.18
  '@platforma-sdk/tengo-builder': ^2.1.13
  '@platforma-sdk/package-builder': ^2.16.2
  '@platforma-sdk/eslint-config': ^1.0.3
  '@milaboratories/graph-maker': ^1.1.137

  '@milaboratories/software-pframes-conv': ^2.2.2
  '@platforma-open/milaboratories.runenv-python-3': ^1.1.16

  'sass-embedded': ^1.77.8

  'vue': ^3.5.13
  'vue-tsc': ^2.2.10

  'typescript': ~5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.5.4

  'vite': ^6.2.2
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  'js-yaml': ^4.1.0

  '@changesets/cli': ^2.28.1
